tableName: cqww_battle_buckets
primaryKey: bucket_id
selector: type="cqww_battle_bucket"
timeQuantumType: YMD
timeQuantumField: bucket_start
attributes:
- fieldName: bucket_id
  sourceName: /data/bucket_id
  mappingStrategy: IntBSI
  type: Integer
  columnID: true
  sourceOrdinal: 1
- fieldName: case_id
  sourceName: /data/case_id
  mappingStrategy: StringEnum
  type: String
  sourceOrdinal: 2
- fieldName: scoring_model
  sourceName: /data/scoring_model
  mappingStrategy: StringEnum
  type: String
  sourceOrdinal: 3
- fieldName: bucket_start
  sourceName: /data/bucket_start
  mappingStrategy: TimestampBSI
  configuration: {granularity: second}
  type: DateTime
  sourceOrdinal: 4
- fieldName: bucket_end
  sourceName: /data/bucket_end
  mappingStrategy: TimestampBSI
  configuration: {granularity: second}
  type: DateTime
  sourceOrdinal: 5
- fieldName: station_call
  sourceName: /data/station_call
  mappingStrategy: StringLexBSI
  configuration: {length: "8"}
  type: String
  maxLen: 16
  sourceOrdinal: 6
- fieldName: leader_call
  sourceName: /data/leader_call
  mappingStrategy: StringLexBSI
  configuration: {length: "8"}
  type: String
  maxLen: 16
  sourceOrdinal: 7
- fieldName: score_behind_leader
  sourceName: /data/score_behind_leader
  mappingStrategy: IntBSI
  type: Integer
  sourceOrdinal: 8
- fieldName: leader_margin
  sourceName: /data/leader_margin
  mappingStrategy: IntBSI
  type: Integer
  sourceOrdinal: 9
- fieldName: bucket_qsos
  sourceName: /data/bucket_qsos
  mappingStrategy: IntBSI
  type: Integer
  sourceOrdinal: 10
- fieldName: bucket_counted_qsos
  sourceName: /data/bucket_counted_qsos
  mappingStrategy: IntBSI
  type: Integer
  sourceOrdinal: 11
- fieldName: bucket_duplicates
  sourceName: /data/bucket_duplicates
  mappingStrategy: IntBSI
  type: Integer
  sourceOrdinal: 12
- fieldName: bucket_points
  sourceName: /data/bucket_points
  mappingStrategy: IntBSI
  type: Integer
  sourceOrdinal: 13
- fieldName: bucket_countries
  sourceName: /data/bucket_countries
  mappingStrategy: IntBSI
  type: Integer
  sourceOrdinal: 14
- fieldName: bucket_zones
  sourceName: /data/bucket_zones
  mappingStrategy: IntBSI
  type: Integer
  sourceOrdinal: 15
- fieldName: bucket_10m
  sourceName: /data/bucket_10m
  mappingStrategy: IntBSI
  type: Integer
  sourceOrdinal: 16
- fieldName: bucket_15m
  sourceName: /data/bucket_15m
  mappingStrategy: IntBSI
  type: Integer
  sourceOrdinal: 17
- fieldName: bucket_20m
  sourceName: /data/bucket_20m
  mappingStrategy: IntBSI
  type: Integer
  sourceOrdinal: 18
- fieldName: bucket_40m
  sourceName: /data/bucket_40m
  mappingStrategy: IntBSI
  type: Integer
  sourceOrdinal: 19
- fieldName: bucket_80m
  sourceName: /data/bucket_80m
  mappingStrategy: IntBSI
  type: Integer
  sourceOrdinal: 20
- fieldName: bucket_160m
  sourceName: /data/bucket_160m
  mappingStrategy: IntBSI
  type: Integer
  sourceOrdinal: 21
- fieldName: cumulative_qsos
  sourceName: /data/cumulative_qsos
  mappingStrategy: IntBSI
  type: Integer
  sourceOrdinal: 22
- fieldName: cumulative_counted_qsos
  sourceName: /data/cumulative_counted_qsos
  mappingStrategy: IntBSI
  type: Integer
  sourceOrdinal: 23
- fieldName: cumulative_duplicates
  sourceName: /data/cumulative_duplicates
  mappingStrategy: IntBSI
  type: Integer
  sourceOrdinal: 24
- fieldName: cumulative_points
  sourceName: /data/cumulative_points
  mappingStrategy: IntBSI
  type: Integer
  sourceOrdinal: 25
- fieldName: cumulative_countries
  sourceName: /data/cumulative_countries
  mappingStrategy: IntBSI
  type: Integer
  sourceOrdinal: 26
- fieldName: cumulative_zones
  sourceName: /data/cumulative_zones
  mappingStrategy: IntBSI
  type: Integer
  sourceOrdinal: 27
- fieldName: cumulative_multipliers
  sourceName: /data/cumulative_multipliers
  mappingStrategy: IntBSI
  type: Integer
  sourceOrdinal: 28
- fieldName: cumulative_score
  sourceName: /data/cumulative_score
  mappingStrategy: IntBSI
  type: Integer
  sourceOrdinal: 29
