tableName: qrz_callsigns
primaryKey: callsign
selector: type="qrz_callsign"
attributes:
- fieldName: callsign
  sourceName: /data/callsign
  mappingStrategy: StringLexBSI
  configuration:
    length: "16"
  type: String
  maxLen: 16
  sourceOrdinal: 1
- fieldName: dxcc_id
  sourceName: /data/dxcc_id
  mappingStrategy: IntBSI
  type: Integer
  sourceOrdinal: 2
- fieldName: dxcc_prefix
  sourceName: /data/dxcc_prefix
  mappingStrategy: StringEnum
  type: String
  sourceOrdinal: 3
- fieldName: continent
  sourceName: /data/continent
  mappingStrategy: StringEnum
  type: String
  sourceOrdinal: 4
- fieldName: country_name
  sourceName: /data/country_name
  mappingStrategy: StringEnum
  type: String
  sourceOrdinal: 5
- fieldName: country_code
  sourceName: /data/country_code
  mappingStrategy: IntBSI
  type: Integer
  sourceOrdinal: 6
- fieldName: first_name
  sourceName: /data/first_name
  mappingStrategy: StringEnum
  type: String
  sourceOrdinal: 7
- fieldName: last_name
  sourceName: /data/last_name
  mappingStrategy: StringEnum
  type: String
  sourceOrdinal: 8
- fieldName: state
  sourceName: /data/state
  mappingStrategy: StringEnum
  type: String
  sourceOrdinal: 9
- fieldName: county
  sourceName: /data/county
  mappingStrategy: StringEnum
  type: String
  sourceOrdinal: 10
- fieldName: grid
  sourceName: /data/grid
  mappingStrategy: StringEnum
  type: String
  sourceOrdinal: 11
- fieldName: latitude
  sourceName: /data/latitude
  mappingStrategy: FloatScaleBSI
  type: Float
  scale: 4
  sourceOrdinal: 12
- fieldName: longitude
  sourceName: /data/longitude
  mappingStrategy: FloatScaleBSI
  type: Float
  scale: 4
  sourceOrdinal: 13
- fieldName: cq_zone
  sourceName: /data/cq_zone
  mappingStrategy: IntBSI
  type: Integer
  sourceOrdinal: 14
- fieldName: itu_zone
  sourceName: /data/itu_zone
  mappingStrategy: IntBSI
  type: Integer
  sourceOrdinal: 15
- fieldName: license_issue_date
  sourceName: /data/license_issue_date
  mappingStrategy: TimestampBSI
  configuration:
    granularity: "second"
  type: Date
  sourceOrdinal: 16
- fieldName: license_exp_date
  sourceName: /data/license_exp_date
  mappingStrategy: TimestampBSI
  configuration:
    granularity: "second"
  type: Date
  sourceOrdinal: 17
- fieldName: lookup_status
  sourceName: /data/lookup_status
  mappingStrategy: StringEnum
  type: String
  sourceOrdinal: 18
- fieldName: lookup_time
  sourceName: /data/lookup_time
  mappingStrategy: TimestampBSI
  configuration:
    granularity: "second"
  type: DateTime
  sourceOrdinal: 19
