tableName: contest_logs
primaryKey: log_id
selector: type="contest_log"
attributes:
- fieldName: log_id
  sourceName: /data/log_id
  mappingStrategy: StringLexBSI
  configuration:
    length: "16"
  type: String
  maxLen: 96
  sourceOrdinal: 1
- fieldName: contest_id
  sourceName: /data/contest_id
  mappingStrategy: StringEnum
  type: String
  sourceOrdinal: 2
- fieldName: station_call
  sourceName: /data/station_call
  mappingStrategy: StringLexBSI
  configuration:
    length: "8"
  type: String
  maxLen: 16
  sourceOrdinal: 3
- fieldName: station_prefix
  sourceName: /data/station_prefix
  mappingStrategy: StringEnum
  type: String
  sourceOrdinal: 4
- fieldName: station_continent
  sourceName: /data/station_continent
  mappingStrategy: StringEnum
  type: String
  sourceOrdinal: 5
- fieldName: station_country
  sourceName: /data/station_country
  mappingStrategy: StringEnum
  type: String
  sourceOrdinal: 6
- fieldName: cq_zone
  sourceName: /data/cq_zone
  mappingStrategy: IntBSI
  type: Integer
  sourceOrdinal: 7
- fieldName: itu_zone
  sourceName: /data/itu_zone
  mappingStrategy: IntBSI
  type: Integer
  sourceOrdinal: 8
- fieldName: category_operator
  sourceName: /data/category_operator
  mappingStrategy: StringEnum
  type: String
  sourceOrdinal: 9
- fieldName: category_assisted
  sourceName: /data/category_assisted
  mappingStrategy: StringEnum
  type: String
  sourceOrdinal: 10
- fieldName: category_band
  sourceName: /data/category_band
  mappingStrategy: StringEnum
  type: String
  sourceOrdinal: 11
- fieldName: category_power
  sourceName: /data/category_power
  mappingStrategy: StringEnum
  type: String
  sourceOrdinal: 12
- fieldName: category_mode
  sourceName: /data/category_mode
  mappingStrategy: StringEnum
  type: String
  sourceOrdinal: 13
- fieldName: category_transmitter
  sourceName: /data/category_transmitter
  mappingStrategy: StringEnum
  type: String
  sourceOrdinal: 14
- fieldName: claimed_score
  sourceName: /data/claimed_score
  mappingStrategy: IntBSI
  type: Integer
  sourceOrdinal: 15
- fieldName: qso_count
  sourceName: /data/qso_count
  mappingStrategy: IntBSI
  type: Integer
  sourceOrdinal: 16
- fieldName: scope_region
  sourceName: /data/scope_region
  mappingStrategy: StringEnum
  type: String
  sourceOrdinal: 17
- fieldName: source_file
  sourceName: /data/source_file
  mappingStrategy: StringLexBSI
  configuration:
    length: "16"
  type: String
  maxLen: 160
  sourceOrdinal: 18
- fieldName: loaded_at
  sourceName: /data/loaded_at
  mappingStrategy: TimestampBSI
  configuration:
    granularity: "second"
  type: DateTime
  sourceOrdinal: 19
