tableName: rbn_spotter_nodes
primaryKey: spotter_call
selector: type="rbn_spotter_node"
attributes:
- fieldName: spotter_call
  sourceName: /data/spotter_call
  mappingStrategy: StringLexBSI
  configuration:
    length: "8"
  type: String
  maxLen: 16
  sourceOrdinal: 1
- fieldName: spotter_prefix
  sourceName: /data/spotter_prefix
  mappingStrategy: StringEnum
  type: String
  sourceOrdinal: 2
- fieldName: spotter_continent
  sourceName: /data/spotter_continent
  mappingStrategy: StringEnum
  type: String
  sourceOrdinal: 3
- fieldName: grid
  sourceName: /data/grid
  mappingStrategy: StringLexBSI
  configuration:
    length: "8"
  type: String
  maxLen: 16
  sourceOrdinal: 4
- fieldName: latitude
  sourceName: /data/latitude
  mappingStrategy: FloatScaleBSI
  type: Float
  scale: 4
  sourceOrdinal: 5
- fieldName: longitude
  sourceName: /data/longitude
  mappingStrategy: FloatScaleBSI
  type: Float
  scale: 4
  sourceOrdinal: 6
- fieldName: geo_source
  sourceName: /data/geo_source
  mappingStrategy: StringEnum
  type: String
  sourceOrdinal: 7
- fieldName: geo_confidence
  sourceName: /data/geo_confidence
  mappingStrategy: StringEnum
  type: String
  sourceOrdinal: 8
- fieldName: dxcc_id
  sourceName: /data/dxcc_id
  mappingStrategy: IntBSI
  type: Integer
  sourceOrdinal: 9
- fieldName: country_name
  sourceName: /data/country_name
  mappingStrategy: StringEnum
  type: String
  sourceOrdinal: 10
- fieldName: cq_zone
  sourceName: /data/cq_zone
  mappingStrategy: IntBSI
  type: Integer
  sourceOrdinal: 11
- fieldName: itu_zone
  sourceName: /data/itu_zone
  mappingStrategy: IntBSI
  type: Integer
  sourceOrdinal: 12
- fieldName: bands
  sourceName: /data/bands
  mappingStrategy: StringEnum
  type: String
  sourceOrdinal: 13
- fieldName: skimmer_software
  sourceName: /data/skimmer_software
  mappingStrategy: StringEnum
  type: String
  sourceOrdinal: 14
- fieldName: aggregator_software
  sourceName: /data/aggregator_software
  mappingStrategy: StringEnum
  type: String
  sourceOrdinal: 15
- fieldName: first_seen_at
  sourceName: /data/first_seen_at
  mappingStrategy: TimestampBSI
  configuration:
    granularity: "second"
  type: DateTime
  sourceOrdinal: 16
- fieldName: last_seen_at
  sourceName: /data/last_seen_at
  mappingStrategy: TimestampBSI
  configuration:
    granularity: "second"
  type: DateTime
  sourceOrdinal: 17
- fieldName: source
  sourceName: /data/source
  mappingStrategy: StringEnum
  type: String
  sourceOrdinal: 18
- fieldName: loaded_at
  sourceName: /data/loaded_at
  mappingStrategy: TimestampBSI
  configuration:
    granularity: "second"
  type: DateTime
  sourceOrdinal: 19
