create or replace view spotter_profile_base as
select
  p.spotter_call as spotter_call,
  p.spotter_prefix as spotter_prefix,
  p.spotter_continent as spotter_continent,
  p.country_name as country_name,
  p.cq_zone as cq_zone,
  p.itu_zone as itu_zone,
  p.latitude as latitude,
  p.longitude as longitude,
  p.geo_source as geo_source,
  p.geo_confidence as geo_confidence,
  p.profile_kind as profile_kind,
  p.window_start as window_start,
  p.window_end as window_end,
  p.total_spots as total_spots,
  p.active_days as active_days,
  p.active_hours as active_hours,
  p.distinct_dx_calls as distinct_dx_calls,
  p.distinct_dx_prefixes as distinct_dx_prefixes,
  p.avg_signal_db as avg_signal_db,
  p.min_signal_db as min_signal_db,
  p.max_signal_db as max_signal_db,
  p.p50_signal_db as p50_signal_db,
  p.p90_signal_db as p90_signal_db,
  p.spotter_weight as spotter_weight,
  p.normalization_offset_db as normalization_offset_db,
  p.profile_quality as profile_quality,
  p.source_table as source_table,
  p.profile_computed_at as profile_computed_at
from spotter_profiles as p;
