create or replace view station_activity_5m_base as
select
  s.summary_id as summary_id,
  s.summary_key as summary_key,
  s.activity_5m_id as activity_5m_id,
  s.activity_5m_ref as activity_5m_ref,
  s.activity_5m_key as activity_5m_key,
  s.bucket_key as bucket_key,
  s.bucket_start as bucket_start,
  year(s.bucket_start) as bucket_year,
  mm(s.bucket_start) as bucket_month,
  day(s.bucket_start) as bucket_day,
  dayofweek(s.bucket_start) as bucket_day_of_week,
  hourofday(s.bucket_start) as bucket_hour,
  s.dx_call as dx_call,
  s.dx_prefix as dx_prefix,
  s.dx_continent as dx_continent,
  s.band as band,
  s.mode as mode,
  s.spotter_continent as spotter_continent,
  s.spot_count as spot_count,
  s.distinct_spotters as distinct_spotters,
  s.distinct_spotter_prefixes as distinct_spotter_prefixes,
  s.avg_signal_db as avg_signal_db,
  s.min_signal_db as min_signal_db,
  s.max_signal_db as max_signal_db,
  s.p50_signal_db as p50_signal_db,
  s.p90_signal_db as p90_signal_db,
  s.reach_score as reach_score,
  s.source_table as source_table,
  s.computed_at as computed_at
from station_activity_5m_summaries as s;
